version: '4.12.0'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: videostream
      POSTGRES_USER: videostream_user
      POSTGRES_PASSWORD: Vs3papCgCyZrIxF2rVkNWmWXYboOy4eX

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 StreaminApp.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
