# Generated by Django 5.0.6 on 2024-05-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoStream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='minutes',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='video',
            name='year_of_release',
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
